### ISSUE TITLE
Dragging didn't work

### ISSUE THREAD

**Issue by suujia** [crclayton/ubc-ssc-transcripter#1]
Thanks for the tool!! :) was really useful. Was a bit confusing "dragging" instructions, can update with more details if you'd like. I'm on chrome but I had to copy the link address then save it as a bookmark. Before that I was playing around with javascript console trying to make it work lol (oops)

Can be a really useful tool for many people!!

**Comment by crclayton** [comment]
Like so:

![drag](https://i.imgur.com/G33FsKF.gif)
